name: rettulf
description: Write widgets in reverse! Rettulf provides lots of wrappers for you build widgets with method chaining.
version: 3.0.0
homepage: https://github.com/liplum/rettulf
repository: https://github.com/liplum/rettulf
issue_tracker: https://github.com/liplum/rettulf/issues


environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
